version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: pull.sh
      timeout: 200
  AfterInstall:
    - location: stop.sh
      timeout: 200
  ApplicationStart:
    - location: start.sh
      timeout: 200
